{{- if and .Values.scheduler.worker.enabled .Values.scheduler.worker.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "aerie.fullname" . }}-scheduler-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aerie.componentLabels" (dict "root" . "component" "scheduler-worker") | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "aerie.fullname" . }}-scheduler-worker
  minReplicas: {{ .Values.scheduler.worker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.scheduler.worker.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.scheduler.worker.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
