{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "aerie.fullname" . }}-migrations
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aerie.componentLabels" (dict "root" . "component" "migrations") | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "aerie.componentSelectorLabels" (dict "root" . "component" "migrations") | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z {{ include "aerie.postgresql.host" . }} {{ include "aerie.postgresql.port" . }}; do echo waiting for postgres; sleep 2; done']
      containers:
        - name: migrations
          image: {{ include "aerie.image" (dict "root" . "repository" .Values.migrations.image.repository "tag" .Values.migrations.image.tag) | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          command:
            - /bin/bash
            - -c
            - |
              set -e
              echo "Running Aerie database migrations..."

              export PGPASSWORD="$AERIE_PASSWORD"

              DB_HOST="{{ include "aerie.postgresql.host" . }}"
              DB_PORT="{{ include "aerie.postgresql.port" . }}"
              DB_NAME="{{ include "aerie.postgresql.database" . }}"

              # Check if migrations have already been applied by looking for the merlin schema
              SCHEMA_EXISTS=$(psql -t -A \
                --host="$DB_HOST" \
                --port="$DB_PORT" \
                --username="$AERIE_USERNAME" \
                --dbname="$DB_NAME" \
                -c "SELECT EXISTS(SELECT 1 FROM information_schema.schemata WHERE schema_name = 'merlin');")

              if [ "$SCHEMA_EXISTS" = "t" ]; then
                echo "Migrations already applied (merlin schema exists). Skipping."
                exit 0
              fi

              echo "Applying database migrations..."

              # Run the SQL migrations with psql variables set
              psql -v ON_ERROR_STOP=1 \
                -v aerie_user="$AERIE_USERNAME" \
                -v gateway_user="$GATEWAY_DB_USER" \
                -v merlin_user="$MERLIN_DB_USER" \
                -v scheduler_user="$SCHEDULER_DB_USER" \
                -v sequencing_user="$SEQUENCING_DB_USER" \
                --host="$DB_HOST" \
                --port="$DB_PORT" \
                --username="$AERIE_USERNAME" \
                --dbname="$DB_NAME" \
                -f /docker-entrypoint-initdb.d/sql/init.sql

              echo "Migrations completed successfully!"
          env:
            - name: AERIE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "aerie.postgresql.secretName" . }}
                  key: aerie-user
            - name: AERIE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "aerie.postgresql.secretName" . }}
                  key: aerie-password
            # These are needed by the SQL scripts for GRANT statements
            - name: GATEWAY_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "aerie.postgresql.secretName" . }}
                  key: gateway-user
            - name: MERLIN_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "aerie.postgresql.secretName" . }}
                  key: merlin-user
            - name: SCHEDULER_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "aerie.postgresql.secretName" . }}
                  key: scheduler-user
            - name: SEQUENCING_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "aerie.postgresql.secretName" . }}
                  key: sequencing-user
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
