{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "aerie.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aerie.labels" . | nindent 4 }}
spec:
  gateways:
    - {{ .Values.istio.gateway }}
  hosts:
    - {{ .Values.istio.host }}
  http:
    # UI - serves the main application (catch-all, must be last)
    # But we define specific routes first, then UI as fallback

    # Hasura GraphQL endpoint
    - match:
        - uri:
            prefix: /v1/graphql
        - uri:
            prefix: /v1/query
        - uri:
            prefix: /v1/metadata
        - uri:
            prefix: /console
        - uri:
            prefix: /v1/version
      corsPolicy:
        {{- toYaml .Values.istio.corsPolicy | nindent 8 }}
      route:
        - destination:
            host: {{ include "aerie.fullname" . }}-hasura
            port:
              number: {{ .Values.hasura.service.port }}

    # Gateway API
    - match:
        - uri:
            prefix: /api/
      corsPolicy:
        {{- toYaml .Values.istio.corsPolicy | nindent 8 }}
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ include "aerie.fullname" . }}-gateway
            port:
              number: {{ .Values.gateway.service.port }}

    # Gateway root endpoints (health, auth, file operations)
    - match:
        - uri:
            prefix: /auth/
        - uri:
            prefix: /file
        - uri:
            exact: /health
      corsPolicy:
        {{- toYaml .Values.istio.corsPolicy | nindent 8 }}
      route:
        - destination:
            host: {{ include "aerie.fullname" . }}-gateway
            port:
              number: {{ .Values.gateway.service.port }}

    # Action server
    - match:
        - uri:
            prefix: /action/
      corsPolicy:
        {{- toYaml .Values.istio.corsPolicy | nindent 8 }}
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ include "aerie.fullname" . }}-action
            port:
              number: {{ .Values.action.port }}

    # Workspace server
    - match:
        - uri:
            prefix: /workspace/
      corsPolicy:
        {{- toYaml .Values.istio.corsPolicy | nindent 8 }}
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ include "aerie.fullname" . }}-workspace
            port:
              number: {{ .Values.workspace.port }}

    # UI - default route (must be last)
    - match:
        - uri:
            prefix: /
      corsPolicy:
        {{- toYaml .Values.istio.corsPolicy | nindent 8 }}
      route:
        - destination:
            host: {{ include "aerie.fullname" . }}-ui
            port:
              number: {{ .Values.ui.service.port }}
{{- end }}
