{{/*
Shared file store PVC - used by Merlin, Scheduler, Sequencing, Gateway, Action
*/}}
{{- if .Values.fileStore.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aerie.fileStore.pvcName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aerie.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.fileStore.accessMode }}
  {{- if .Values.fileStore.storageClass }}
  storageClassName: {{ .Values.fileStore.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.fileStore.size }}
{{- end }}
---
{{/*
Workspace file store PVC
*/}}
{{- if and .Values.workspace.enabled .Values.workspace.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aerie.workspace.pvcName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aerie.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.workspace.persistence.accessMode }}
  {{- if .Values.workspace.persistence.storageClass }}
  storageClassName: {{ .Values.workspace.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.workspace.persistence.size }}
{{- end }}
---
{{/*
PostgreSQL data PVC (only if internal postgres is enabled)
*/}}
{{- if and .Values.postgresql.enabled .Values.postgresql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aerie.postgres.pvcName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aerie.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.postgresql.persistence.accessMode }}
  {{- if .Values.postgresql.persistence.storageClass }}
  storageClassName: {{ .Values.postgresql.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
{{- end }}
