{{/*
Database credentials secret - only created if not using an existing secret
*/}}
{{- if not (and (not .Values.postgresql.enabled) .Values.externalPostgresql.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aerie.postgresql.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aerie.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgresql.enabled }}
  # Internal PostgreSQL credentials
  postgres-user: {{ .Values.postgresql.auth.postgresUser | quote }}
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | quote }}
  aerie-user: {{ .Values.postgresql.auth.aerieUser | quote }}
  aerie-password: {{ .Values.postgresql.auth.aeriePassword | quote }}
  # Service users - default to aerie credentials when using internal postgres
  merlin-user: "merlin_service"
  merlin-password: {{ .Values.postgresql.auth.aeriePassword | quote }}
  scheduler-user: "scheduler_service"
  scheduler-password: {{ .Values.postgresql.auth.aeriePassword | quote }}
  sequencing-user: "sequencing_service"
  sequencing-password: {{ .Values.postgresql.auth.aeriePassword | quote }}
  gateway-user: "gateway_service"
  gateway-password: {{ .Values.postgresql.auth.aeriePassword | quote }}
  {{- else }}
  # External PostgreSQL credentials
  aerie-user: {{ required "externalPostgresql.auth.aerieUser is required" .Values.externalPostgresql.auth.aerieUser | quote }}
  aerie-password: {{ required "externalPostgresql.auth.aeriePassword is required" .Values.externalPostgresql.auth.aeriePassword | quote }}
  merlin-user: {{ .Values.externalPostgresql.auth.merlinUser | default "merlin_service" | quote }}
  merlin-password: {{ required "externalPostgresql.auth.merlinPassword is required" .Values.externalPostgresql.auth.merlinPassword | quote }}
  scheduler-user: {{ .Values.externalPostgresql.auth.schedulerUser | default "scheduler_service" | quote }}
  scheduler-password: {{ required "externalPostgresql.auth.schedulerPassword is required" .Values.externalPostgresql.auth.schedulerPassword | quote }}
  sequencing-user: {{ .Values.externalPostgresql.auth.sequencingUser | default "sequencing_service" | quote }}
  sequencing-password: {{ required "externalPostgresql.auth.sequencingPassword is required" .Values.externalPostgresql.auth.sequencingPassword | quote }}
  gateway-user: {{ .Values.externalPostgresql.auth.gatewayUser | default "gateway_service" | quote }}
  gateway-password: {{ required "externalPostgresql.auth.gatewayPassword is required" .Values.externalPostgresql.auth.gatewayPassword | quote }}
  {{- end }}
{{- end }}
---
{{/*
Hasura secrets - only created if not using an existing secret
*/}}
{{- if not .Values.hasura.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aerie.fullname" . }}-hasura-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aerie.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-secret: {{ .Values.hasura.adminSecret | quote }}
  jwt-secret: {{ .Values.hasura.jwtSecret | quote }}
{{- end }}
